name: Deploy snapshot

on:
  workflow_call:
  
jobs:
  build:
    # Should only deploy snapshots for branches
    if: github.ref_type == 'branch'

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      # Step that does that actual cache save and restore
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
           ${{ runner.os }}-maven-

      - name: install git secrets
        run: |
          wget --no-verbose -O git-secrets-1.3.0.tar.gz https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
          tar -zxf git-secrets-1.3.0.tar.gz
          cd git-secrets-1.3.0
          sudo make install   

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2+13.0.LTS'
          distribution: 'adopt'
          # settings.xml configuration
          server-id: 'snapshots'
          server-username: SNAPSHOT_DEPLOY_USERNAME
          server-password: SNAPSHOT_DEPLOY_TOKEN

      - name: Deploy with mvnw
        run: |
          if [ ${{ github.ref_name }} == develop ]; then
            ./mvnw --batch-mode deploy -ntp -DskipTests
          else
            CHANGELIST_VERSION=.0-${{ github.ref_name }}-SNAPSHOT
            CHANGELIST_VERSION=${CHANGELIST_VERSION//\//_}
            ./mvnw --batch-mode deploy -ntp -DskipTests -Dchangelist=$CHANGELIST_VERSION
          fi
        env: 
          SNAPSHOT_DEPLOY_USERNAME: 'dockstore-snapshot-bot'
          SNAPSHOT_DEPLOY_TOKEN: ${{ secrets.SNAPSHOT_DEPLOY_TOKEN }}
